// 图标组件索引文件
export { default as IconNewFile } from './IconNewFile.vue'
export { default as IconOpenFolder } from './IconOpenFolder.vue'
export { default as IconSave } from './IconSave.vue'
export { default as IconPrint } from './IconPrint.vue'
export { default as IconSearch } from './IconSearch.vue'
export { default as IconZoomIn } from './IconZoomIn.vue'
export { default as IconZoomOut } from './IconZoomOut.vue'
export { default as IconFitToScreen } from './IconFitToScreen.vue'
export { default as IconDrag } from './IconDrag.vue'
export { default as IconArrowUp } from './IconArrowUp.vue'
export { default as IconArrowRight } from './IconArrowRight.vue'
export { default as IconNorthPole } from './IconNorthPole.vue'
export { default as IconCompass } from './IconCompass.vue'
export { default as IconBreak } from './IconBreak.vue'
export { default as IconDiscrete } from './IconDiscrete.vue'
export { default as IconHeatmapEarth } from './IconHeatmapEarth.vue'
export { default as IconLatLonEarth } from './IconLatLonEarth.vue'
export { default as IconGridEarth } from './IconGridEarth.vue'
export { default as IconAngleMeasurement } from './IconAngleMeasurement.vue'
export { default as IconSlopeMeasurement } from './IconSlopeMeasurement.vue'
export { default as IconCone } from './IconCone.vue'
export { default as IconExclude } from './IconExclude.vue'
export { default as IconAddText } from './IconAddText.vue'
export { default as IconSitArrow } from './IconSitArrow.vue'
export { default as IconOvalBox } from './IconOvalBox.vue'
export { default as IconSlash } from './IconSlash.vue'
export { default as IconIncompleteHexagon } from './IconIncompleteHexagon.vue'
export { default as IconRegularHexagon } from './IconRegularHexagon.vue'

// 原有的图标组件
export { default as IconCommunity } from './IconCommunity.vue'
export { default as IconDocumentation } from './IconDocumentation.vue'
export { default as IconEcosystem } from './IconEcosystem.vue'
export { default as IconSupport } from './IconSupport.vue'
export { default as IconTooling } from './IconTooling.vue'
